// Known security audit report sources — messengers, crypto, web, mobile, infrastructure

export interface AuditSource {
  id: string;
  firm: string;
  target: string;
  year: number;
  url: string;
  type: "pdf" | "html" | "github";
  description: string;
}

export const auditSources: AuditSource[] = [
  // ═══ Trail of Bits ═══════════════════════════════════════════
  {
    id: "tob-simplex-2024",
    firm: "Trail of Bits",
    target: "SimpleX Chat",
    year: 2024,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/SimpleXChat.pdf",
    type: "pdf",
    description: "Security review of SimpleX Chat SMP protocol and Haskell implementation",
  },
  {
    id: "tob-whatsapp-2025",
    firm: "Trail of Bits",
    target: "WhatsApp Private Processing",
    year: 2025,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/2025-08-meta-whatsapp-privateprocessing-securityreview.pdf",
    type: "pdf",
    description: "Security review of Meta WhatsApp Private Processing",
  },
  {
    id: "tob-standardnotes",
    firm: "Trail of Bits",
    target: "Standard Notes",
    year: 2022,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/StandardNotes.pdf",
    type: "pdf",
    description: "Security review of Standard Notes encrypted note-taking app",
  },
  {
    id: "tob-mobilecoin",
    firm: "Trail of Bits",
    target: "MobileCoin",
    year: 2020,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/Mobilecoin.pdf",
    type: "pdf",
    description: "Security review of MobileCoin (used by Signal for payments)",
  },
  {
    id: "tob-mobilecoin-fog",
    firm: "Trail of Bits",
    target: "MobileCoin Fog",
    year: 2021,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/MobilecoinFog.pdf",
    type: "pdf",
    description: "Security review of MobileCoin Fog — private payment retrieval",
  },
  {
    id: "tob-mobilecoin-bft",
    firm: "Trail of Bits",
    target: "MobileCoin BFT",
    year: 2022,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/MobileCoinBFT.pdf",
    type: "pdf",
    description: "Audit of MobileCoin BFT consensus protocol",
  },
  {
    id: "tob-mobilecoin-2022",
    firm: "Trail of Bits",
    target: "MobileCoin",
    year: 2022,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/2022-07-mobilecoin-securityreview.pdf",
    type: "pdf",
    description: "Follow-up security review of MobileCoin platform",
  },
  {
    id: "tob-zcash",
    firm: "Trail of Bits",
    target: "Zcash",
    year: 2020,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/Zcash.pdf",
    type: "pdf",
    description: "Security review of Zcash privacy cryptocurrency",
  },
  {
    id: "tob-zcash-2",
    firm: "Trail of Bits",
    target: "Zcash",
    year: 2021,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/Zcash2.pdf",
    type: "pdf",
    description: "Second security review of Zcash",
  },
  {
    id: "tob-zerotier",
    firm: "Trail of Bits",
    target: "ZeroTier Protocol",
    year: 2020,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/ZeroTierProtocol.pdf",
    type: "pdf",
    description: "Security review of ZeroTier peer-to-peer networking protocol",
  },
  {
    id: "tob-sweetb",
    firm: "Trail of Bits",
    target: "SweetB Crypto Library",
    year: 2020,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/SweetB.pdf",
    type: "pdf",
    description: "Audit of SweetB cryptographic library — ECC, constant-time ops",
  },
  {
    id: "tob-spruceID",
    firm: "Trail of Bits",
    target: "SpruceID",
    year: 2022,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/SpruceID.pdf",
    type: "pdf",
    description: "Security review of SpruceID — decentralized identity, DID",
  },
  {
    id: "tob-securitdropworkstation",
    firm: "Trail of Bits",
    target: "SecureDrop Workstation",
    year: 2020,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/SecureDropWorkstation.pdf",
    type: "pdf",
    description: "Security review of SecureDrop Workstation for journalists",
  },
  {
    id: "tob-curl-2022",
    firm: "Trail of Bits",
    target: "curl",
    year: 2022,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/2022-12-curl-securityreview.pdf",
    type: "pdf",
    description: "Security review of curl — TLS, HTTP, memory safety",
  },
  {
    id: "tob-openvpn-2022",
    firm: "Trail of Bits",
    target: "OpenVPN 2",
    year: 2022,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/2022-12-openvpn-openvpn2-securityreview.pdf",
    type: "pdf",
    description: "Security review of OpenVPN 2 — VPN protocol, crypto, memory safety",
  },
  {
    id: "tob-walletconnect-2023",
    firm: "Trail of Bits",
    target: "WalletConnect v2",
    year: 2023,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/2023-03-walletconnectv2-securityreview.pdf",
    type: "pdf",
    description: "Security review of WalletConnect v2 — secure pairing protocol",
  },
  {
    id: "tob-keda-2023",
    firm: "Trail of Bits",
    target: "KEDA",
    year: 2023,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/2023-01-keda-securityreview.pdf",
    type: "pdf",
    description: "Security review of KEDA — Kubernetes event-driven autoscaler",
  },
  {
    id: "tob-prysm-2023",
    firm: "Trail of Bits",
    target: "Prysm",
    year: 2023,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/2023-04-prysm-securityreview.pdf",
    type: "pdf",
    description: "Security review of Prysm Ethereum consensus client (Go)",
  },
  {
    id: "tob-flux-2023",
    firm: "Trail of Bits",
    target: "Flux CD",
    year: 2023,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/2023-08-flux-securityreview.pdf",
    type: "pdf",
    description: "Security review of Flux CD GitOps toolkit",
  },
  {
    id: "tob-homebrew-2023",
    firm: "Trail of Bits",
    target: "Homebrew",
    year: 2023,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/2023-08-28-homebrew-securityreview.pdf",
    type: "pdf",
    description: "Security review of Homebrew package manager",
  },
  {
    id: "tob-etcd",
    firm: "Trail of Bits",
    target: "etcd",
    year: 2020,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/etcd.pdf",
    type: "pdf",
    description: "Security review of etcd — distributed key-value store, Raft consensus",
  },
  {
    id: "tob-parity",
    firm: "Trail of Bits",
    target: "Parity",
    year: 2018,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/parity.pdf",
    type: "pdf",
    description: "Security review of Parity Ethereum client (Rust)",
  },
  {
    id: "tob-voatz",
    firm: "Trail of Bits",
    target: "Voatz",
    year: 2019,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/voatz-securityreview.pdf",
    type: "pdf",
    description: "Security review of Voatz mobile voting — TEE, crypto, auth",
  },
  {
    id: "tob-tekton",
    firm: "Trail of Bits",
    target: "Tekton",
    year: 2022,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/Tekton.pdf",
    type: "pdf",
    description: "Security review of Tekton CI/CD framework for Kubernetes",
  },
  {
    id: "tob-osquery",
    firm: "Trail of Bits",
    target: "osquery",
    year: 2019,
    url: "https://raw.githubusercontent.com/trailofbits/publications/master/reviews/osquery.pdf",
    type: "pdf",
    description: "Security review of osquery system monitoring framework",
  },
  // ═══ Cure53 ══════════════════════════════════════════════════
  {
    id: "cure53-briar-2017",
    firm: "Cure53",
    target: "Briar",
    year: 2017,
    url: "https://cure53.de/pentest-report_briar.pdf",
    type: "pdf",
    description: "Pentest of Briar messenger — Tor transport timing, JNI unsafe pointers",
  },
  {
    id: "cure53-threema",
    firm: "Cure53",
    target: "Threema",
    year: 2020,
    url: "https://cure53.de/pentest-report_threema.pdf",
    type: "pdf",
    description: "Security audit of Threema cryptographic library and apps",
  },
  {
    id: "cure53-threema-desktop",
    firm: "Cure53",
    target: "Threema Desktop",
    year: 2022,
    url: "https://cure53.de/pentest-report_threema-desktop.pdf",
    type: "pdf",
    description: "Security audit of Threema Desktop application",
  },
  {
    id: "cure53-flowcrypt",
    firm: "Cure53",
    target: "FlowCrypt",
    year: 2020,
    url: "https://cure53.de/pentest-report_flowcrypt.pdf",
    type: "pdf",
    description: "Audit of FlowCrypt — PGP email encryption for Gmail",
  },
  {
    id: "cure53-pgpainless",
    firm: "Cure53",
    target: "PGPainless",
    year: 2022,
    url: "https://cure53.de/pentest-report_pgpainless.pdf",
    type: "pdf",
    description: "Audit of PGPainless Java OpenPGP library",
  },
  {
    id: "cure53-rnp",
    firm: "Cure53",
    target: "RNP (Thunderbird PGP)",
    year: 2021,
    url: "https://cure53.de/pentest-report_rnp.pdf",
    type: "pdf",
    description: "Audit of RNP OpenPGP library used by Thunderbird — C++, memory safety",
  },
  {
    id: "cure53-rustls",
    firm: "Cure53",
    target: "rustls",
    year: 2022,
    url: "https://cure53.de/pentest-report_rustls.pdf",
    type: "pdf",
    description: "Audit of rustls — Rust TLS library, protocol conformance, memory safety",
  },
  {
    id: "cure53-rust-libs-2022",
    firm: "Cure53",
    target: "Rust Crypto Libraries",
    year: 2022,
    url: "https://cure53.de/pentest-report_rust-libs_2022.pdf",
    type: "pdf",
    description: "Audit of Rust crypto libraries — ed25519, x25519, chacha20poly1305",
  },
  {
    id: "cure53-ed25519",
    firm: "Cure53",
    target: "ed25519-dalek",
    year: 2021,
    url: "https://cure53.de/pentest-report_ed25519.pdf",
    type: "pdf",
    description: "Audit of ed25519-dalek Rust library — signature verification, constant-time",
  },
  {
    id: "cure53-noble-crypto",
    firm: "Cure53",
    target: "noble crypto libs",
    year: 2022,
    url: "https://cure53.de/pentest-report_noble-lib.pdf",
    type: "pdf",
    description: "Audit of noble JavaScript crypto libraries — ed25519, secp256k1",
  },
  {
    id: "cure53-hashing-libs",
    firm: "Cure53",
    target: "Hashing Libraries",
    year: 2022,
    url: "https://cure53.de/pentest-report_hashing-libs.pdf",
    type: "pdf",
    description: "Audit of cryptographic hashing libraries",
  },
  {
    id: "cure53-monocypher",
    firm: "Cure53",
    target: "Monocypher",
    year: 2021,
    url: "https://cure53.de/pentest-report_monocypher.pdf",
    type: "pdf",
    description: "Audit of Monocypher C crypto library — ChaCha20, Poly1305, X25519, EdDSA",
  },
  {
    id: "cure53-1password-core-2021",
    firm: "Cure53",
    target: "1Password Core",
    year: 2021,
    url: "https://cure53.de/pentest-report_1password-core-2021.pdf",
    type: "pdf",
    description: "Audit of 1Password core — SRP auth, key derivation, vault encryption",
  },
  {
    id: "cure53-1password-b5",
    firm: "Cure53",
    target: "1Password Browser",
    year: 2020,
    url: "https://cure53.de/pentest-report_1password-b5.pdf",
    type: "pdf",
    description: "Audit of 1Password browser extension — autofill XSS, DOM injection",
  },
  {
    id: "cure53-1password-mobile",
    firm: "Cure53",
    target: "1Password Mobile",
    year: 2020,
    url: "https://cure53.de/pentest-report_1password-mobile.pdf",
    type: "pdf",
    description: "Audit of 1Password iOS/Android — biometric auth, keychain, clipboard",
  },
  {
    id: "cure53-proton-pass",
    firm: "Cure53",
    target: "Proton Pass",
    year: 2023,
    url: "https://cure53.de/pentest-report_proton-pass.pdf",
    type: "pdf",
    description: "Audit of Proton Pass password manager",
  },
  {
    id: "cure53-keepassium",
    firm: "Cure53",
    target: "KeePassium",
    year: 2023,
    url: "https://cure53.de/pentest-report_keepassium.pdf",
    type: "pdf",
    description: "Audit of KeePassium — KeePass iOS client, database handling",
  },
  {
    id: "cure53-passbolt-backend",
    firm: "Cure53",
    target: "Passbolt Backend",
    year: 2022,
    url: "https://cure53.de/pentest-report_passbolt-backend.pdf",
    type: "pdf",
    description: "Audit of Passbolt password manager backend — PHP, API, GPG",
  },
  {
    id: "cure53-passbolt-extensions",
    firm: "Cure53",
    target: "Passbolt Extensions",
    year: 2022,
    url: "https://cure53.de/pentest-report_passbolt-extensions.pdf",
    type: "pdf",
    description: "Audit of Passbolt browser extensions",
  },
  {
    id: "cure53-mozilla-vpn",
    firm: "Cure53",
    target: "Mozilla VPN",
    year: 2021,
    url: "https://cure53.de/pentest-report_mozilla-vpn.pdf",
    type: "pdf",
    description: "Audit of Mozilla VPN — WireGuard, multi-platform clients",
  },
  {
    id: "cure53-mullvad-2024",
    firm: "Cure53",
    target: "Mullvad VPN",
    year: 2024,
    url: "https://cure53.de/pentest-report_mullvad_2024_v1.pdf",
    type: "pdf",
    description: "Security audit of Mullvad VPN — WireGuard, tunnel leak, DNS",
  },
  {
    id: "cure53-mullvad-2021",
    firm: "Cure53",
    target: "Mullvad VPN",
    year: 2021,
    url: "https://cure53.de/pentest-report_mullvad_2021_v1.pdf",
    type: "pdf",
    description: "Security audit of Mullvad VPN",
  },
  {
    id: "cure53-nordvpn-apps",
    firm: "Cure53",
    target: "NordVPN Apps",
    year: 2022,
    url: "https://cure53.de/pentest-report_nordvpn-apps-addons.pdf",
    type: "pdf",
    description: "Audit of NordVPN applications and add-ons",
  },
  {
    id: "cure53-nordvpn-infra",
    firm: "Cure53",
    target: "NordVPN Infrastructure",
    year: 2022,
    url: "https://cure53.de/pentest-report_nordvpn-infra.pdf",
    type: "pdf",
    description: "Audit of NordVPN server infrastructure",
  },
  {
    id: "cure53-expressvpn-lightway-2024",
    firm: "Cure53",
    target: "ExpressVPN Lightway",
    year: 2024,
    url: "https://cure53.de/pentest-report_expressvpn-lightway_2024.pdf",
    type: "pdf",
    description: "Audit of ExpressVPN Lightway protocol — WolfSSL, DTLS, tunnel",
  },
  {
    id: "cure53-expressvpn-android",
    firm: "Cure53",
    target: "ExpressVPN Android",
    year: 2022,
    url: "https://cure53.de/pentest-report_expressvpn-android.pdf",
    type: "pdf",
    description: "Audit of ExpressVPN Android app — VPN leak, split tunnel, Kotlin",
  },
  {
    id: "cure53-expressvpn-ios",
    firm: "Cure53",
    target: "ExpressVPN iOS",
    year: 2022,
    url: "https://cure53.de/pentest-report_expressvpn-ios.pdf",
    type: "pdf",
    description: "Audit of ExpressVPN iOS app",
  },
  {
    id: "cure53-expressvpn-keys",
    firm: "Cure53",
    target: "ExpressVPN Keys",
    year: 2023,
    url: "https://cure53.de/pentest-report_expressvpn-keys-extension.pdf",
    type: "pdf",
    description: "Audit of ExpressVPN Keys password manager extension",
  },
  {
    id: "cure53-ivpn-2024",
    firm: "Cure53",
    target: "IVPN",
    year: 2024,
    url: "https://cure53.de/pentest-report_IVPN_2024.pdf",
    type: "pdf",
    description: "Security audit of IVPN — WireGuard, multi-hop, DNS",
  },
  {
    id: "cure53-ivpn-2023",
    firm: "Cure53",
    target: "IVPN",
    year: 2023,
    url: "https://cure53.de/pentest-report_IVPN_2023.pdf",
    type: "pdf",
    description: "Security audit of IVPN",
  },
  {
    id: "cure53-tunnelbear-2023",
    firm: "Cure53",
    target: "TunnelBear",
    year: 2023,
    url: "https://cure53.de/pentest-report_tunnelbear_2023.pdf",
    type: "pdf",
    description: "Audit of TunnelBear VPN",
  },
  {
    id: "cure53-pomerium",
    firm: "Cure53",
    target: "Pomerium",
    year: 2022,
    url: "https://cure53.de/pentest-report_pomerium.pdf",
    type: "pdf",
    description: "Audit of Pomerium zero-trust access proxy",
  },
  {
    id: "cure53-safing-jess",
    firm: "Cure53",
    target: "Safing Jess",
    year: 2022,
    url: "https://cure53.de/pentest-report_safing-jess.pdf",
    type: "pdf",
    description: "Audit of Safing Jess cryptographic tool suite",
  },
  {
    id: "cure53-dapr",
    firm: "Cure53",
    target: "Dapr",
    year: 2022,
    url: "https://cure53.de/pentest-report_dapr.pdf",
    type: "pdf",
    description: "Audit of Dapr — distributed application runtime, microservices security",
  },
  {
    id: "cure53-tikv",
    firm: "Cure53",
    target: "TiKV",
    year: 2022,
    url: "https://cure53.de/pentest-report_tikv.pdf",
    type: "pdf",
    description: "Audit of TiKV distributed key-value store (Rust)",
  },
  {
    id: "cure53-contour",
    firm: "Cure53",
    target: "Contour",
    year: 2022,
    url: "https://cure53.de/pentest-report_contour.pdf",
    type: "pdf",
    description: "Audit of Contour — Kubernetes ingress controller",
  },
  {
    id: "cure53-psiphon-4",
    firm: "Cure53",
    target: "Psiphon",
    year: 2023,
    url: "https://cure53.de/pentest-report_psiphon_4.pdf",
    type: "pdf",
    description: "Audit of Psiphon censorship circumvention tool",
  },
  {
    id: "cure53-authentik",
    firm: "Cure53",
    target: "authentik",
    year: 2023,
    url: "https://cure53.de/pentest-report_authentik.pdf",
    type: "pdf",
    description: "Audit of authentik — open-source identity provider, SAML, OIDC, LDAP",
  },
  {
    id: "cure53-ente-crypto",
    firm: "Cure53",
    target: "Ente Crypto",
    year: 2023,
    url: "https://cure53.de/audit-report_ente-crypto.pdf",
    type: "pdf",
    description: "Audit of Ente encrypted photo storage — E2E encryption, key management",
  },
  {
    id: "cure53-nym",
    firm: "Cure53",
    target: "Nym",
    year: 2023,
    url: "https://cure53.de/audit-report_nym.pdf",
    type: "pdf",
    description: "Audit of Nym mixnet — anonymous communication, Sphinx packets",
  },
  {
    id: "cure53-nip44",
    firm: "Cure53",
    target: "NIP-44 (Nostr Encryption)",
    year: 2024,
    url: "https://cure53.de/audit-report_nip44-implementations.pdf",
    type: "pdf",
    description: "Audit of NIP-44 encrypted direct messages for Nostr protocol",
  },
  {
    id: "cure53-php-saml",
    firm: "Cure53",
    target: "PHP SAML SP",
    year: 2022,
    url: "https://cure53.de/pentest-report_php-saml-sp.pdf",
    type: "pdf",
    description: "Audit of PHP SAML Service Provider — XML signature, auth bypass",
  },
  {
    id: "cure53-formsg",
    firm: "Cure53",
    target: "FormSG",
    year: 2022,
    url: "https://cure53.de/pentest-report_formsg.pdf",
    type: "pdf",
    description: "Audit of FormSG — Singapore gov form builder, end-to-end encryption",
  },
  // ═══ Cure53 — Audit Reports ══════════════════════════════════
  {
    id: "cure53-coinbase-kms",
    firm: "Cure53",
    target: "Coinbase KMS",
    year: 2023,
    url: "https://cure53.de/audit-report_coinbase-kms.pdf",
    type: "pdf",
    description: "Audit of Coinbase key management system",
  },
  {
    id: "cure53-noble-crypto-audit",
    firm: "Cure53",
    target: "noble crypto libs",
    year: 2023,
    url: "https://cure53.de/audit-report_noble-crypto-libs.pdf",
    type: "pdf",
    description: "Audit of noble-curves, noble-hashes — JS crypto primitives",
  },
  // ═══ Kudelski Security ═══════════════════════════════════════
  {
    id: "kudelski-wire-2018",
    firm: "Kudelski Security",
    target: "Wire",
    year: 2018,
    url: "https://wire-docs.wire.com/download/Wire+Security+Whitepaper.pdf",
    type: "pdf",
    description: "Security review of Wire's Proteus protocol — nonce reuse, group messaging",
  },
  // ═══ Academic ════════════════════════════════════════════════
  {
    id: "ncc-telegram-2021",
    firm: "NCC Group / Academic",
    target: "Telegram MTProto",
    year: 2021,
    url: "https://mtpsym.github.io/paper.pdf",
    type: "pdf",
    description: "Academic/NCC analysis of Telegram MTProto 2.0 — symmetric crypto issues",
  },
  {
    id: "ruhr-matrix-2023",
    firm: "Ruhr University Bochum",
    target: "Matrix (Megolm)",
    year: 2023,
    url: "https://nebuchadnezzar-megolm.github.io/static/paper.pdf",
    type: "pdf",
    description: "Academic: Megolm attacks — confidentiality break, key forwarding, impersonation",
  },
];

/** Get all sources, optionally filtered */
export function getSources(filter?: { firm?: string; target?: string }): AuditSource[] {
  let sources = auditSources;
  if (filter?.firm) {
    sources = sources.filter((s) => s.firm.toLowerCase().includes(filter.firm!.toLowerCase()));
  }
  if (filter?.target) {
    sources = sources.filter((s) => s.target.toLowerCase().includes(filter.target!.toLowerCase()));
  }
  return sources;
}
